import 'package:dhikr/src/features/dhikr/domain/dhikr.dart';

const azkarPages = [
  Dhikr(id: '1', imageUrl: 'assets/images/pages/p1.jpg', description: 'description'),
  Dhikr(id: '2', imageUrl: 'assets/images/pages/p2.jpg', description: 'description'),
  Dhikr(id: '3', imageUrl: 'assets/images/pages/p3.jpg', description: 'description'),
  Dhikr(id: '4', imageUrl: 'assets/images/pages/p4.jpg', description: 'description'),
  Dhikr(id: '5', imageUrl: 'assets/images/pages/p5.jpg', description: 'description'),
  Dhikr(id: '6', imageUrl: 'assets/images/pages/p6.jpg', description: 'description'),
  Dhikr(id: '7', imageUrl: 'assets/images/pages/p7.jpg', description: 'description'),
  Dhikr(id: '8', imageUrl: 'assets/images/pages/p8.jpg', description: 'description'),
  Dhikr(id: '9', imageUrl: 'assets/images/pages/p9.jpg', description: 'description'),
  Dhikr(id: '10', imageUrl: 'assets/images/pages/p10.jpg', description: 'description'),
  Dhikr(id: '11', imageUrl: 'assets/images/pages/p11.jpg', description: 'description'),
  Dhikr(id: '12', imageUrl: 'assets/images/pages/p12.jpg', description: 'description'),
  Dhikr(id: '13', imageUrl: 'assets/images/pages/p13.jpg', description: 'description'),
  Dhikr(id: '14', imageUrl: 'assets/images/pages/p14.jpg', description: 'description'),
  Dhikr(id: '15', imageUrl: 'assets/images/pages/p15.jpg', description: 'description'),
  Dhikr(id: '16', imageUrl: 'assets/images/pages/p16.jpg', description: 'description'),
  Dhikr(id: '17', imageUrl: 'assets/images/pages/p17.jpg', description: 'description'),
  Dhikr(id: '18', imageUrl: 'assets/images/pages/p18.jpg', description: 'description'),
  Dhikr(id: '19', imageUrl: 'assets/images/pages/p19.jpg', description: 'description'),
  Dhikr(id: '20', imageUrl: 'assets/images/pages/p20.jpg', description: 'description'),
  Dhikr(id: '21', imageUrl: 'assets/images/pages/p21.jpg', description: 'description'),
  Dhikr(id: '22', imageUrl: 'assets/images/pages/p22.jpg', description: 'description'),
  Dhikr(id: '23', imageUrl: 'assets/images/pages/p23.jpg', description: 'description'),
  Dhikr(id: '24', imageUrl: 'assets/images/pages/p24.jpg', description: 'description'),
  Dhikr(id: '25', imageUrl: 'assets/images/pages/p25.jpg', description: 'description'),
  Dhikr(id: '26', imageUrl: 'assets/images/pages/p26.jpg', description: 'description'),
  Dhikr(id: '27', imageUrl: 'assets/images/pages/p27.jpg', description: 'description'),
  Dhikr(id: '28', imageUrl: 'assets/images/pages/p28.jpg', description: 'description'),
  Dhikr(id: '29', imageUrl: 'assets/images/pages/p29.jpg', description: 'description'),
  Dhikr(id: '30', imageUrl: 'assets/images/pages/p30.jpg', description: 'description'),
  Dhikr(id: '31', imageUrl: 'assets/images/pages/p31.jpg', description: 'description'),
  Dhikr(id: '32', imageUrl: 'assets/images/pages/p32.jpg', description: 'description'),
  Dhikr(id: '33', imageUrl: 'assets/images/pages/p33.jpg', description: 'description'),
];
